### ISSUE TITLE
AttributeError while trying to install woke and fuzz a simple contract

### ISSUE THREAD

**Issue by ivanpostolski** [Ackee-Blockchain/woke#157]
Hello

I'm looking to give it a try to woke fuzzer. I got the following contract in Solidity: 

```
pragma solidity ^0.8.9;

contract Subject {

    uint x = 0;

    mapping(uint256 => address) policies;

    event new_policy(uint nr,address to);
    event del_policy(uint nr);

    function newPolicy(address to) public returns(bool,uint){
        policies[x++] = to;
        emit new_policy(x,to);
        return (true,x);
    }

    function resolvePolicy() payable public returns(bool){
        delete policies[x];
        emit del_policy(x);
        return true;
    }

}
```
I've installed woke though the command 

`pip install "abch-woke[fuzzer]"`

with python version 3.7 under a fresh python environment made using venv

Then executed 

`woke init fuzz`

That output these two warnings: 

`WARNING  2022-09-13 14:27:11,762 woke.config.woke_config: Config file '/home/ivan/.config/Woke/config.toml' does not exist.                                                                woke_config.py:95`
`WARNING  2022-09-13 14:27:11,767 woke.config.woke_config: Config file '/home/ivan/woke/examples/woke.toml' does not exist.`

Then wrote this dummy file at tests/test_example.py (which was not automatically created, as the docs say)

```
from random import random
import IPython
import brownie

from pytypes import SubjectType

from woke.fuzzer import Campaign
from woke.fuzzer.decorators import (
    flow,
    ignore,
    invariant,
    max_times,
    precondition,
    weight,
)
from woke.fuzzer.random import (
    random_account,
    random_bool,
    random_bytes,
    random_int,
    random_string,
)


class TestingSequence:
    def __init__(self, contract: SubjectType):
        self.owner = random_account()
        self.contract = contract.deploy({"from":self.owner})
        self.subjects = {}

    @flow
    def flow_test_example(self):
        pass

    @invariant
    def invariant_test_example(self):
        pass


def test_example():
    campaign = Campaign(lambda: TestingSequence(SubjectType))
    campaign.run(1000, 400)
```
and when trying to perform 

`woke fuzz`

it fails with the error: 

`AttributeError: type object 'SubjectType' has no attribute 'deploy' at the deploy call line`

Please let me know if you can reproduce the error and what should I do different. 

Thanks

**Comment by michprev** [comment]
Hello,
thank you for your interest in our tool!

We've been able to reproduce your issue with `test_example.py` not being actually created and it will be fixed in the next release, thank you.

Regarding the issue with `deploy` not being an attribute of `'SubjectType'`, please start with the following code:
```py
from random import random
import IPython
import brownie

from pytypes import SubjectType

from woke.fuzzer import Campaign
from woke.fuzzer.decorators import (
    flow,
    ignore,
    invariant,
    max_times,
    precondition,
    weight,
)
from woke.fuzzer.random import (
    random_account,
    random_bool,
    random_bytes,
    random_int,
    random_string,
)


class TestingSequence:
    def __init__(self, contract: SubjectType):
        self.owner = random_account()
        self.contract = contract.deploy({"from":self.owner})
        self.subjects = {}

    @flow
    def flow_test_example(self):
        pass

    @invariant
    def invariant_test_example(self):
        pass


def test_example(Subject):
    campaign = Campaign(lambda: TestingSequence(Subject))
    campaign.run(1000, 400)
```

Explanation:
`SubjectType` generated in pytypes is there to speed up tests creation - it provides typing suggestions but does not implement any of the methods documented by Brownie. This is why we use classes from pytypes in Python static typing, but the real underlying object is not of the `SubjectType` but of the `Subject` type (created at runtime by Brownie).

Please see https://eth-brownie.readthedocs.io/en/stable/tests-pytest-fixtures.html#contract-fixtures for more info.

Agree this is confusing and in fact, this is one of the reasons why we decided to leave Brownie as a dependency for our fuzzer and implement our own testing framework for Solidity written in Python. Stay tuned for updates!

**Comment by ivanpostolski** [comment]
Awesome! Thank you. It works and makes sense.

Regarding fuzzing, does woke supports any kind of white box inspection? I'm thinking something like [afl-cov ](https://github.com/mrash/afl-cov) that measures coverage while fuzzing. If not, do you think it would be hard to implementing it using brownie coverage capabilities?

**Comment by michprev** [comment]
Coverage preview is on our TODO list. We would like to display coverage data through our VS Code extension (will be released soon). However, it will not be part of the first release. It should include both information about coverage in functions (how many times has been a given if branch visited as percentage) and information about how many times has been a given function visited in comparison to other functions.
![image](https://user-images.githubusercontent.com/7281754/191520640-41be554c-7538-4f5c-b575-da7d6f9a56d5.png)

Due to fuzzing performance reasons, it will not be recommended to have the coverage feature always enabled.
