### ISSUE TITLE
file path autocompletion not currently available in `woke` CLI?

### ISSUE THREAD

**Issue by mmsaki** [Ackee-Blockchain/woke#253]
Woke has auto-completion for CLI commands, which is great, but I notice that if you want to add a file path as an argument then the auto-completion using `TAB` is not available. Is there a different key binding for that?

<img width="997" alt="Screenshot 2023-07-15 at 5 25 46 PM" src="https://github.com/Ackee-Blockchain/woke/assets/98189596/4f28874a-dcdb-49c6-9c7b-5f5c6d76189d">

**Comment by michprev** [comment]
Yeah, this is a special case of the `woke test` command where we wanted to implement a passthrough mode for `pytest` so that any CLI options unrecognized by Woke would be passed to `pytest`. In the end, filesystem auto-completions nor passthrough mode work. Both will be fixed in the next version, the fix is already prepared in https://github.com/Ackee-Blockchain/woke/commit/9d92bb57614491aaa54a3d1d706b21dc49c7b70e.

**Comment by michprev** [comment]
Fixed in v3.5.0.
